const int endingConsonantClustersFreq[ 
    NUM_ENDING_CONSONANT_CLUSTERS ] = {
    1,      // nched
    2,      // ngued
    1,      // ngues
    1,      // rched
    1,      // rscht
    4,      // tched
    3,      // bbed
    12,      // ched
    17,      // cked
    12,      // dged
    4,      // ffed
    15,      // gged
    1,      // ghth
    6,      // ghts
    9,      // gned
    3,      // gued
    1,      // gues
    1,      // lfth
    3,      // lged
    1,      // lked
    67,      // lled
    1,      // lmed
    1,      // lque
    2,      // lsed
    12,      // lved
    7,      // lves
    3,      // mbed
    9,      // mmed
    1,      // mned
    3,      // mped
    1,      // mpse
    21,      // nced
    2,      // nche
    1,      // ncts
    1,      // ndth
    22,      // nged
    2,      // ngst
    2,      // ngth
    3,      // ngue
    3,      // nked
    17,      // nned
    6,      // nsed
    1,      // nstr
    1,      // nthe
    1,      // ntze
    28,      // pped
    1,      // ppes
    3,      // psed
    1,      // qued
    5,      // rbed
    6,      // rced
    15,      // rged
    1,      // rgne
    1,      // rgue
    7,      // rked
    3,      // rled
    1,      // rles
    12,      // rmed
    1,      // rmth
    12,      // rned
    1,      // rpse
    4,      // rque
    30,      // rred
    1,      // rsch
    15,      // rsed
    1,      // rsts
    8,      // rved
    3,      // rves
    5,      // sced
    15,      // shed
    2,      // sked
    9,      // sque
    21,      // ssed
    9,      // thed
    2,      // thes
    2,      // tsch
    1,      // ttes
    3,      // wned
    1,      // wnst
    10,      // bed
    1,      // bel
    2,      // bes
    1,      // ble
    54,      // ced
    16,      // che
    1,      // cht
    16,      // cks
    1,      // cts
    1,      // dds
    8,      // des
    45,      // dge
    2,      // dst
    4,      // dth
    3,      // fed
    2,      // ffe
    4,      // ffs
    1,      // fth
    29,      // ged
    126,      // ght
    4,      // gne
    25,      // gue
    2,      // hns
    23,      // ked
    5,      // kes
    7,      // lch
    1,      // lct
    1,      // lds
    1,      // ldt
    86,      // led
    10,      // les
    2,      // lft
    5,      // lge
    36,      // lle
    9,      // lls
    2,      // lms
    1,      // lph
    1,      // lpt
    6,      // lse
    2,      // lsh
    1,      // lte
    6,      // lth
    2,      // lts
    1,      // ltz
    19,      // lve
    1,      // mbs
    38,      // med
    3,      // mes
    2,      // mme
    5,      // mph
    4,      // mps
    10,      // mpt
    218,      // nce
    51,      // nch
    11,      // nct
    4,      // nde
    16,      // nds
    86,      // ned
    12,      // nes
    39,      // nge
    33,      // ngs
    1,      // nkh
    7,      // nks
    2,      // nne
    1,      // nns
    23,      // nse
    1,      // nst
    5,      // nte
    26,      // nth
    9,      // nts
    2,      // ntz
    1,      // nze
    14,      // ped
    10,      // pes
    1,      // phs
    3,      // ppe
    9,      // pse
    1,      // pth
    21,      // que
    1,      // rbs
    15,      // rce
    26,      // rch
    1,      // rck
    1,      // rcs
    1,      // rct
    2,      // rde
    12,      // rds
    145,      // red
    6,      // res
    37,      // rge
    3,      // rgh
    7,      // rks
    2,      // rld
    1,      // rme
    4,      // rms
    9,      // rne
    4,      // rns
    5,      // rnt
    1,      // rps
    1,      // rpt
    3,      // rre
    2,      // rrh
    53,      // rse
    3,      // rsh
    16,      // rst
    3,      // rte
    22,      // rth
    8,      // rts
    5,      // rtz
    13,      // rve
    1,      // rze
    10,      // sce
    105,      // sed
    2,      // sle
    1,      // sne
    11,      // sse
    19,      // ste
    1,      // str
    1,      // sts
    64,      // tch
    2,      // ted
    12,      // tes
    23,      // the
    3,      // thm
    38,      // tte
    1,      // ttn
    2,      // tts
    52,      // ved
    18,      // ves
    10,      // wed
    1,      // wls
    2,      // wns
    3,      // wse
    4,      // wth
    12,      // xed
    1,      // xth
    68,      // zed
    1,      // bb
    45,      // be
    8,      // bs
    3,      // bt
    166,      // ce
    86,      // ch
    307,      // ck
    70,      // cs
    150,      // ct
    3,      // dd
    275,      // de
    1,      // dh
    1,      // dl
    23,      // ds
    1,      // dz
    24,      // fe
    73,      // ff
    2,      // fs
    60,      // ft
    127,      // ge
    1,      // gg
    36,      // gh
    4,      // gm
    26,      // gn
    9,      // gs
    3,      // hm
    5,      // hn
    1,      // hr
    3,      // hs
    1,      // ht
    180,      // ke
    3,      // ks
    3,      // lb
    1,      // lc
    119,      // ld
    211,      // le
    23,      // lf
    42,      // lk
    248,      // ll
    17,      // lm
    3,      // ln
    8,      // lp
    23,      // ls
    78,      // lt
    32,      // mb
    160,      // me
    9,      // mn
    58,      // mp
    35,      // ms
    2,      // mt
    4,      // nc
    340,      // nd
    472,      // ne
    2917,      // ng
    91,      // nk
    4,      // nn
    86,      // ns
    953,      // nt
    12,      // nx
    92,      // pe
    32,      // ph
    3,      // pp
    30,      // ps
    60,      // pt
    21,      // rb
    1,      // rc
    276,      // rd
    386,      // re
    8,      // rf
    17,      // rg
    112,      // rk
    29,      // rl
    91,      // rm
    139,      // rn
    14,      // rp
    6,      // rr
    118,      // rs
    167,      // rt
    2,      // sc
    336,      // se
    345,      // sh
    25,      // sk
    241,      // sm
    17,      // sp
    1119,      // ss
    1154,      // st
    2,      // sz
    800,      // te
    129,      // th
    51,      // ts
    14,      // tt
    6,      // tz
    450,      // ve
    2,      // vt
    5,      // wd
    9,      // wk
    28,      // wl
    90,      // wn
    1,      // wp
    16,      // ws
    1,      // wt
    1,      // xe
    5,      // xt
    155,      // ze
    7,      // zz
    99,      // b
    915,      // c
    2093,      // d
    65,      // f
    149,      // g
    40,      // h
    136,      // k
    1706,      // l
    625,      // m
    2726,      // n
    357,      // p
    2,      // q
    4592,      // r
    1504,      // s
    983,      // t
    11,      // v
    261,      // w
    138,      // x
    6 };      // z
