const int middleConsonantClustersFreq[ 
    NUM_MIDDLE_CONSONANT_CLUSTERS ] = {
    1,      // ckscr
    5,      // ckstr
    1,      // ckthr
    1,      // ffspr
    1,      // ghtcl
    1,      // ghtdr
    3,      // ghtsh
    1,      // ghtsp
    1,      // ghtst
    1,      // lkscr
    1,      // llspr
    1,      // llstr
    1,      // lmstr
    1,      // mbscr
    1,      // mpstr
    1,      // ndspr
    1,      // ndthr
    1,      // ngspr
    2,      // ngstr
    1,      // ngthw
    1,      // rkscr
    1,      // rstwh
    1,      // rthpl
    2,      // rthst
    1,      // rthwh
    1,      // rtstr
    1,      // rtthr
    1,      // stscr
    1,      // ststr
    2,      // tchbl
    1,      // tchcr
    2,      // wnstr
    4,      // bscr
    13,      // bstr
    1,      // chsh
    1,      // chst
    1,      // ckbr
    1,      // ckcl
    1,      // ckcr
    1,      // ckdr
    1,      // ckgr
    2,      // ckkn
    1,      // ckpr
    1,      // cksc
    5,      // cksh
    2,      // cksk
    2,      // cksl
    3,      // cksm
    3,      // cksp
    7,      // ckst
    1,      // cksw
    1,      // ckth
    1,      // cktr
    1,      // ckwh
    2,      // dspr
    3,      // dstr
    1,      // dthw
    1,      // ffpr
    2,      // ffsh
    1,      // ffst
    3,      // ftsm
    1,      // ggpl
    1,      // ggsh
    4,      // ghbr
    1,      // ghsh
    1,      // ghtb
    1,      // ghtc
    9,      // ghtf
    1,      // ghtg
    4,      // ghth
    17,      // ghtl
    2,      // ghtm
    5,      // ghtn
    2,      // ghtr
    1,      // ghts
    1,      // ghtt
    5,      // ghtw
    1,      // kthr
    2,      // lchr
    1,      // ldbr
    2,      // ldsm
    1,      // ldsp
    2,      // ldst
    1,      // lfsb
    1,      // lfsk
    2,      // llbl
    3,      // llfl
    1,      // llfr
    1,      // llgr
    1,      // llpl
    1,      // llsp
    3,      // llst
    1,      // llwr
    2,      // lmsh
    1,      // lmsm
    1,      // lptr
    2,      // lstr
    1,      // lthf
    1,      // ltst
    1,      // mbpr
    1,      // mbsh
    1,      // mbsk
    1,      // mbst
    1,      // mpbl
    1,      // mpcr
    1,      // mpgr
    1,      // mphl
    1,      // mpsh
    2,      // mpst
    1,      // mptb
    1,      // mptl
    1,      // mptn
    2,      // mptr
    2,      // mscr
    2,      // mstr
    2,      // nchb
    2,      // nchl
    4,      // nchm
    2,      // nchp
    6,      // nchr
    1,      // ncht
    1,      // nchw
    3,      // nctl
    2,      // ndbl
    1,      // ndbr
    2,      // ndch
    1,      // ndcl
    1,      // ndcr
    1,      // ndfl
    1,      // ndgr
    2,      // ndpr
    3,      // ndsc
    3,      // ndsh
    1,      // ndsl
    3,      // ndsm
    1,      // ndsp
    7,      // ndst
    1,      // ndsw
    1,      // ndtr
    2,      // ndwr
    1,      // ngpl
    4,      // ngsh
    1,      // ngsp
    10,      // ngst
    7,      // ngth
    1,      // ngwr
    1,      // nkbl
    1,      // nksg
    2,      // nksh
    1,      // nkst
    1,      // nsch
    15,      // nscr
    2,      // nsgr
    4,      // nshr
    1,      // nspl
    2,      // nspr
    2,      // nssh
    40,      // nstr
    1,      // ntbr
    1,      // ntcl
    3,      // nthl
    15,      // nthr
    1,      // ntsm
    1,      // ntsv
    6,      // phth
    2,      // pstr
    1,      // rbst
    1,      // rchb
    3,      // rchd
    1,      // rchf
    2,      // rchg
    2,      // rchl
    2,      // rchm
    1,      // rchn
    3,      // rchw
    1,      // rdbr
    2,      // rdpl
    5,      // rdsh
    3,      // rdsm
    1,      // rdst
    2,      // rksh
    1,      // rksk
    1,      // rksm
    2,      // rksp
    2,      // rksw
    4,      // rldl
    1,      // rldw
    1,      // rlfr
    1,      // rmch
    1,      // rmfr
    1,      // rmst
    1,      // rncr
    1,      // rnfl
    1,      // rnsh
    5,      // rnst
    1,      // rpsm
    1,      // rsch
    2,      // rshl
    1,      // rshm
    1,      // rshn
    1,      // rspl
    2,      // rspr
    1,      // rstb
    1,      // rsth
    2,      // rstl
    4,      // rstr
    2,      // rtbr
    2,      // rthb
    1,      // rthd
    2,      // rthf
    7,      // rthl
    1,      // rthm
    1,      // rthq
    6,      // rthr
    1,      // rths
    9,      // rthw
    1,      // rtsc
    2,      // rtsh
    2,      // rtsm
    1,      // rtst
    1,      // rtsw
    1,      // rtwh
    3,      // schl
    2,      // schm
    2,      // schn
    1,      // schw
    2,      // shcl
    1,      // shst
    1,      // shtr
    1,      // shwh
    2,      // ssbr
    1,      // sscr
    1,      // stgr
    7,      // sthm
    1,      // stpl
    1,      // stpr
    2,      // stwr
    7,      // tchb
    1,      // tchc
    1,      // tchd
    3,      // tchf
    2,      // tchh
    1,      // tchk
    3,      // tchl
    7,      // tchm
    2,      // tchp
    1,      // tcht
    4,      // tchw
    1,      // thbl
    1,      // thbr
    4,      // thdr
    1,      // thpr
    3,      // thst
    1,      // thtr
    1,      // tscr
    1,      // tspr
    4,      // tstr
    1,      // tthr
    1,      // ttsb
    1,      // ttsd
    1,      // ttsf
    1,      // tzkr
    1,      // wnbr
    2,      // wngr
    1,      // wnsf
    2,      // wnsh
    1,      // wnsm
    2,      // wnsp
    4,      // wnst
    1,      // wnsw
    2,      // wntr
    2,      // wspr
    1,      // wsst
    2,      // wstr
    51,      // bbl
    6,      // bbr
    2,      // bch
    2,      // bcl
    1,      // bcr
    1,      // bdr
    1,      // bfl
    2,      // bgl
    1,      // bgr
    1,      // bph
    1,      // bpl
    16,      // bsc
    3,      // bsl
    1,      // bsp
    25,      // bst
    2,      // btf
    7,      // btl
    7,      // btr
    1,      // bwh
    6,      // cch
    13,      // ccl
    11,      // ccr
    1,      // chd
    1,      // chf
    1,      // chh
    19,      // chl
    8,      // chm
    15,      // chn
    44,      // chr
    3,      // chs
    3,      // cht
    19,      // ckb
    4,      // ckd
    7,      // ckf
    2,      // ckg
    12,      // ckh
    2,      // ckj
    91,      // ckl
    6,      // ckm
    15,      // ckn
    12,      // ckp
    12,      // ckr
    12,      // cks
    6,      // ckt
    14,      // ckw
    2,      // cst
    5,      // ctf
    14,      // ctl
    3,      // ctm
    6,      // ctn
    33,      // ctr
    1,      // dbl
    1,      // dbr
    2,      // dch
    2,      // dcl
    1,      // dcr
    1,      // ddb
    2,      // ddf
    4,      // ddh
    59,      // ddl
    1,      // ddm
    1,      // ddn
    6,      // ddr
    1,      // dfl
    1,      // dfr
    1,      // dgl
    5,      // dgm
    3,      // dhp
    2,      // dph
    6,      // dsh
    2,      // dsk
    1,      // dsl
    3,      // dsm
    1,      // dsp
    13,      // dst
    1,      // dsw
    2,      // ffb
    1,      // ffh
    54,      // ffl
    2,      // ffn
    11,      // ffr
    3,      // ffs
    2,      // fgh
    2,      // fst
    1,      // ftb
    7,      // ftl
    4,      // ftn
    1,      // ftr
    4,      // ftw
    1,      // ggb
    1,      // ggh
    41,      // ggl
    1,      // ggn
    11,      // ggr
    7,      // ghb
    1,      // ghc
    1,      // ghd
    2,      // ghf
    1,      // ghg
    3,      // ghh
    9,      // ghl
    6,      // ghn
    1,      // ghp
    1,      // ghr
    84,      // ght
    2,      // ghw
    1,      // gnb
    2,      // gnl
    2,      // gnm
    1,      // gnp
    1,      // gnt
    2,      // gsh
    1,      // gsk
    5,      // gst
    1,      // gtr
    1,      // gwh
    1,      // hlr
    1,      // hmm
    2,      // hnn
    1,      // hns
    1,      // kch
    1,      // kfr
    1,      // kpl
    2,      // ksh
    2,      // kst
    1,      // lbl
    2,      // lbr
    9,      // lch
    2,      // lcl
    1,      // lcr
    3,      // ldb
    1,      // ldc
    8,      // ldf
    2,      // ldh
    10,      // ldl
    5,      // ldn
    1,      // ldp
    10,      // ldr
    1,      // ldw
    1,      // lfb
    2,      // lfh
    5,      // lfl
    2,      // lfp
    3,      // lfr
    1,      // lfs
    1,      // lft
    2,      // lfw
    4,      // lgr
    1,      // lkb
    1,      // lkh
    2,      // lkl
    2,      // lkm
    4,      // lks
    4,      // lkw
    15,      // llb
    2,      // llc
    10,      // lld
    9,      // llf
    1,      // llg
    9,      // llh
    4,      // llm
    8,      // lln
    6,      // llp
    3,      // llr
    2,      // lls
    2,      // llt
    4,      // llw
    1,      // lmd
    1,      // lmg
    1,      // lml
    1,      // lmn
    1,      // lms
    3,      // lpf
    14,      // lph
    5,      // lpl
    2,      // lpm
    3,      // lpr
    4,      // lpt
    1,      // lpw
    1,      // lsc
    8,      // lsh
    2,      // lsk
    1,      // lsm
    2,      // lsn
    2,      // lsp
    13,      // lst
    1,      // ltb
    1,      // ltc
    1,      // ltf
    18,      // lth
    2,      // ltl
    1,      // ltm
    1,      // ltn
    1,      // ltp
    35,      // ltr
    3,      // ltw
    3,      // ltz
    1,      // mbb
    1,      // mbd
    1,      // mbf
    1,      // mbk
    72,      // mbl
    2,      // mbm
    3,      // mbn
    42,      // mbr
    1,      // mbs
    1,      // mbt
    1,      // mbw
    1,      // mcr
    2,      // mdr
    2,      // mfl
    1,      // mkh
    1,      // mnb
    1,      // mnd
    1,      // mnl
    1,      // mnn
    2,      // mpb
    1,      // mpf
    25,      // mph
    3,      // mpk
    106,      // mpl
    1,      // mpm
    2,      // mpn
    1,      // mpp
    60,      // mpr
    7,      // mps
    51,      // mpt
    1,      // msd
    6,      // msh
    1,      // msk
    1,      // msm
    1,      // msp
    10,      // mst
    6,      // nbl
    11,      // nbr
    88,      // nch
    60,      // ncl
    1,      // ncm
    34,      // ncr
    44,      // nct
    13,      // ndb
    4,      // ndc
    1,      // ndd
    8,      // ndf
    1,      // ndg
    8,      // ndh
    1,      // ndj
    1,      // ndk
    79,      // ndl
    16,      // ndm
    11,      // ndn
    10,      // ndp
    58,      // ndr
    10,      // nds
    18,      // ndw
    37,      // nfl
    22,      // nfr
    8,      // ngb
    6,      // ngd
    9,      // ngf
    17,      // ngh
    2,      // ngk
    227,      // ngl
    4,      // ngm
    4,      // ngn
    1,      // ngp
    59,      // ngr
    3,      // ngs
    10,      // ngt
    2,      // ngw
    1,      // nkb
    1,      // nkc
    12,      // nkf
    1,      // nkg
    5,      // nkh
    29,      // nkl
    2,      // nkm
    12,      // nkn
    3,      // nkr
    2,      // nkt
    1,      // nkw
    1,      // nnk
    1,      // nns
    22,      // npl
    14,      // npr
    2,      // nrh
    1,      // nsb
    22,      // nsc
    3,      // nsd
    18,      // nsf
    33,      // nsh
    6,      // nsk
    16,      // nsl
    22,      // nsm
    7,      // nsn
    41,      // nsp
    92,      // nst
    2,      // nsv
    12,      // nsw
    2,      // ntd
    4,      // ntf
    3,      // ntg
    43,      // nth
    128,      // ntl
    6,      // ntm
    8,      // ntn
    1,      // ntp
    176,      // ntr
    2,      // nts
    6,      // ntw
    4,      // ntz
    3,      // nwh
    9,      // nwr
    3,      // pbr
    1,      // pch
    2,      // pdr
    1,      // pfl
    1,      // pfr
    3,      // pgr
    6,      // phl
    19,      // phr
    2,      // pkn
    2,      // pph
    62,      // ppl
    42,      // ppr
    2,      // psc
    7,      // psh
    2,      // psk
    1,      // psq
    21,      // pst
    1,      // psw
    1,      // ptc
    5,      // ptl
    5,      // ptn
    2,      // ptr
    2,      // pwr
    16,      // rbl
    8,      // rbr
    82,      // rch
    14,      // rcl
    5,      // rcr
    7,      // rct
    7,      // rdb
    1,      // rdc
    2,      // rdf
    6,      // rdh
    30,      // rdl
    2,      // rdm
    5,      // rdn
    1,      // rdp
    14,      // rdr
    2,      // rds
    3,      // rdt
    1,      // rdv
    3,      // rdw
    1,      // rfb
    1,      // rfd
    12,      // rfl
    3,      // rfr
    2,      // rgh
    13,      // rgl
    2,      // rgn
    13,      // rgr
    2,      // rkb
    2,      // rkd
    4,      // rkh
    1,      // rkk
    10,      // rkl
    2,      // rkm
    3,      // rkn
    4,      // rkr
    3,      // rks
    1,      // rkt
    5,      // rkw
    1,      // rld
    1,      // rlh
    1,      // rlp
    1,      // rlw
    1,      // rmb
    4,      // rmf
    4,      // rmh
    12,      // rml
    1,      // rmn
    1,      // rmp
    1,      // rmr
    1,      // rmw
    4,      // rnb
    2,      // rnc
    1,      // rnd
    4,      // rnf
    1,      // rnk
    7,      // rnl
    8,      // rnm
    1,      // rnn
    2,      // rnp
    1,      // rns
    1,      // rnt
    24,      // rph
    17,      // rpl
    1,      // rpm
    1,      // rpn
    20,      // rpr
    4,      // rps
    5,      // rpt
    11,      // rrh
    1,      // rsb
    3,      // rsc
    1,      // rsd
    1,      // rsf
    43,      // rsh
    3,      // rsk
    6,      // rsl
    4,      // rsm
    3,      // rsn
    18,      // rsp
    1,      // rsq
    28,      // rst
    3,      // rsw
    2,      // rtb
    4,      // rtc
    9,      // rtf
    6,      // rtg
    61,      // rth
    38,      // rtl
    8,      // rtm
    13,      // rtn
    14,      // rtr
    5,      // rts
    3,      // rtw
    1,      // rtz
    3,      // rwh
    3,      // rwr
    53,      // sch
    12,      // scl
    134,      // scr
    2,      // sdr
    6,      // sgr
    9,      // shb
    2,      // shc
    1,      // shd
    6,      // shf
    1,      // shh
    1,      // shk
    56,      // shl
    17,      // shm
    12,      // shn
    4,      // shp
    42,      // shr
    4,      // sht
    1,      // shv
    7,      // shw
    1,      // skl
    2,      // skm
    1,      // skn
    1,      // skr
    1,      // spb
    47,      // sph
    44,      // spl
    1,      // spn
    60,      // spr
    8,      // ssb
    1,      // ssc
    6,      // ssf
    3,      // ssh
    1,      // ssk
    41,      // ssl
    13,      // ssm
    5,      // ssn
    8,      // ssp
    4,      // ssr
    5,      // sst
    11,      // ssw
    12,      // stb
    2,      // stc
    4,      // std
    15,      // stf
    20,      // sth
    76,      // stl
    14,      // stm
    10,      // stn
    6,      // stp
    305,      // str
    1,      // sts
    9,      // stw
    2,      // tbl
    4,      // tbr
    95,      // tch
    2,      // tcl
    4,      // tcr
    2,      // tfl
    5,      // tgr
    3,      // thb
    11,      // thf
    5,      // thh
    17,      // thl
    7,      // thm
    6,      // thn
    5,      // thp
    77,      // thr
    4,      // ths
    2,      // tht
    11,      // thw
    2,      // tpl
    2,      // tpr
    1,      // tsb
    3,      // tsc
    10,      // tsh
    2,      // tsk
    3,      // tsm
    2,      // tsp
    6,      // tst
    5,      // tsw
    1,      // tth
    69,      // ttl
    13,      // ttr
    1,      // tts
    1,      // tzp
    1,      // tzv
    6,      // wbr
    1,      // wcl
    6,      // wdl
    2,      // wdn
    10,      // wdr
    3,      // wfl
    2,      // wkn
    2,      // wkw
    1,      // wnb
    1,      // wnc
    2,      // wnf
    2,      // wnh
    1,      // wnp
    2,      // wnr
    3,      // wnt
    2,      // wnw
    2,      // wpl
    1,      // wsb
    2,      // wsc
    1,      // wsd
    1,      // wsg
    3,      // wsh
    3,      // wsl
    1,      // wsm
    3,      // wsp
    1,      // wsr
    1,      // wst
    4,      // wsw
    1,      // wth
    1,      // xbl
    6,      // xch
    9,      // xcl
    10,      // xcr
    1,      // xgl
    28,      // xpl
    7,      // xpr
    1,      // xsw
    1,      // xtb
    31,      // xtr
    28,      // zzl
    1,      // zzm
    205,      // bb
    6,      // bc
    21,      // bd
    7,      // bf
    3,      // bg
    14,      // bh
    27,      // bj
    1,      // bk
    1291,      // bl
    18,      // bm
    18,      // bn
    1,      // bp
    537,      // br
    72,      // bs
    22,      // bt
    12,      // bv
    4,      // bw
    181,      // cc
    4,      // cd
    789,      // ch
    345,      // ck
    447,      // cl
    1,      // cm
    5,      // cn
    21,      // cq
    582,      // cr
    4,      // cs
    549,      // ct
    8,      // cz
    20,      // db
    7,      // dc
    173,      // dd
    16,      // df
    169,      // dg
    23,      // dh
    35,      // dj
    2,      // dk
    187,      // dl
    47,      // dm
    59,      // dn
    10,      // dp
    1,      // dq
    336,      // dr
    20,      // ds
    4,      // dt
    43,      // dv
    41,      // dw
    1,      // dz
    3,      // fb
    1,      // fc
    1,      // fd
    254,      // ff
    1,      // fh
    1,      // fj
    404,      // fl
    4,      // fn
    319,      // fr
    87,      // ft
    9,      // gb
    2,      // gc
    2,      // gd
    3,      // gf
    222,      // gg
    43,      // gh
    1,      // gj
    234,      // gl
    51,      // gm
    212,      // gn
    6,      // gp
    632,      // gr
    1,      // gs
    8,      // gt
    10,      // gw
    3,      // gz
    1,      // hd
    2,      // hl
    3,      // hr
    2,      // jj
    3,      // kb
    1,      // kc
    4,      // kd
    3,      // kf
    8,      // kh
    1,      // kj
    8,      // kk
    22,      // kl
    4,      // km
    78,      // kn
    1,      // kp
    14,      // kr
    1,      // ks
    1,      // kt
    1,      // kv
    6,      // kw
    33,      // lb
    72,      // lc
    118,      // ld
    35,      // lf
    51,      // lg
    7,      // lh
    56,      // lk
    1411,      // ll
    70,      // lm
    28,      // ln
    36,      // lp
    1,      // lq
    16,      // lr
    66,      // ls
    206,      // lt
    120,      // lv
    16,      // lw
    272,      // mb
    8,      // mc
    3,      // md
    20,      // mf
    2,      // mh
    1,      // mj
    36,      // ml
    364,      // mm
    61,      // mn
    445,      // mp
    1,      // mq
    8,      // mr
    19,      // ms
    3,      // mt
    5,      // mv
    5,      // mw
    81,      // nb
    917,      // nc
    922,      // nd
    250,      // nf
    454,      // ng
    109,      // nh
    53,      // nj
    152,      // nk
    151,      // nl
    63,      // nm
    444,      // nn
    54,      // np
    45,      // nq
    101,      // nr
    502,      // ns
    1113,      // nt
    197,      // nv
    70,      // nw
    7,      // nx
    30,      // nz
    11,      // pb
    9,      // pc
    5,      // pd
    8,      // pf
    3,      // pg
    362,      // ph
    2,      // pj
    3,      // pk
    402,      // pl
    14,      // pm
    14,      // pn
    380,      // pp
    910,      // pr
    121,      // ps
    198,      // pt
    10,      // pw
    240,      // rb
    237,      // rc
    259,      // rd
    111,      // rf
    286,      // rg
    80,      // rh
    13,      // rj
    90,      // rk
    288,      // rl
    395,      // rm
    300,      // rn
    121,      // rp
    18,      // rq
    603,      // rr
    372,      // rs
    492,      // rt
    196,      // rv
    58,      // rw
    5,      // rz
    41,      // sb
    513,      // sc
    21,      // sd
    16,      // sf
    17,      // sg
    618,      // sh
    5,      // sj
    158,      // sk
    362,      // sl
    172,      // sm
    141,      // sn
    549,      // sp
    89,      // sq
    22,      // sr
    674,      // ss
    1607,      // st
    6,      // sv
    149,      // sw
    33,      // tb
    12,      // tc
    13,      // td
    38,      // tf
    9,      // tg
    642,      // th
    1,      // tk
    102,      // tl
    27,      // tm
    33,      // tn
    12,      // tp
    793,      // tr
    28,      // ts
    688,      // tt
    3,      // tv
    87,      // tw
    15,      // tz
    5,      // vr
    8,      // vv
    1,      // vz
    27,      // wb
    4,      // wc
    27,      // wd
    15,      // wf
    5,      // wg
    193,      // wh
    9,      // wk
    53,      // wl
    14,      // wm
    56,      // wn
    11,      // wp
    98,      // wr
    24,      // ws
    8,      // wt
    3,      // ww
    8,      // wz
    1,      // xb
    56,      // xc
    3,      // xf
    22,      // xh
    6,      // xl
    2,      // xn
    104,      // xp
    2,      // xq
    60,      // xt
    1,      // xv
    3,      // xw
    1,      // zd
    3,      // zl
    1,      // zm
    2,      // zt
    1,      // zv
    1,      // zw
    49,      // zz
    2995,      // b
    5325,      // c
    4623,      // d
    2200,      // f
    2464,      // g
    1834,      // h
    539,      // j
    838,      // k
    5717,      // l
    4803,      // m
    5346,      // n
    3396,      // p
    423,      // q
    7301,      // r
    4193,      // s
    7226,      // t
    2982,      // v
    1320,      // w
    396,      // x
    837 };      // z
