const int startingVowelClustersFreq[ NUM_STARTING_VOWEL_CLUSTERS ] = {
    1,      // aiia
    1,      // ayee
    1,      // ayey
    1,      // ayoe
    1,      // ayoi
    2,      // ayou
    1,      // eaui
    1,      // eyei
    1,      // eyey
    2,      // iyea
    1,      // oeia
    3,      // ooey
    2,      // ooie
    1,      // oyee
    2,      // oyeu
    3,      // oyou
    3,      // ueou
    1,      // ueue
    1,      // ueui
    1,      // uiou
    1,      // uoia
    3,      // uoya
    1,      // aai
    1,      // aea
    2,      // aeo
    2,      // aeu
    3,      // aia
    3,      // aie
    1,      // aii
    1,      // aoi
    2,      // aou
    2,      // aue
    13,      // aya
    43,      // aye
    22,      // ayi
    22,      // ayo
    4,      // ayu
    1,      // eae
    36,      // eau
    3,      // eea
    14,      // eei
    1,      // eia
    5,      // eio
    3,      // eoi
    56,      // eou
    6,      // eya
    49,      // eye
    9,      // eyi
    5,      // eyo
    5,      // iae
    1,      // iai
    2,      // iao
    1,      // iei
    9,      // ieu
    1,      // ioa
    2,      // ioe
    1,      // ioi
    187,      // iou
    3,      // iya
    1,      // oau
    5,      // oei
    2,      // oeu
    2,      // oia
    1,      // oie
    5,      // ooe
    8,      // ooi
    4,      // oua
    5,      // oue
    4,      // oui
    23,      // oya
    10,      // oye
    6,      // oyi
    3,      // oyo
    8,      // uai
    1,      // uau
    2,      // uay
    14,      // uea
    11,      // uee
    2,      // uei
    1,      // ueu
    3,      // uey
    4,      // uia
    20,      // uie
    1,      // uiu
    5,      // uoi
    43,      // uou
    2,      // uoy
    2,      // uya
    1,      // uye
    3,      // uyi
    8,      // aa
    72,      // ae
    786,      // ai
    13,      // ao
    448,      // au
    296,      // ay
    1742,      // ea
    902,      // ee
    296,      // ei
    194,      // eo
    153,      // eu
    140,      // ey
    1181,      // ia
    2071,      // ie
    3,      // ii
    1341,      // io
    174,      // iu
    353,      // oa
    141,      // oe
    368,      // oi
    891,      // oo
    1408,      // ou
    68,      // oy
    449,      // ua
    392,      // ue
    418,      // ui
    46,      // uo
    6,      // uu
    8,      // uy
    20381,      // a
    30392,      // e
    20256,      // i
    13523,      // o
    7814 };      // u
