# script run on main server to shutdown all servers and update them
# to the latest binary server code.  Does NOT update game data for the servers.


# shuts down each server and rebuilds them, one by one, allowing
# players to continue playing on the other servers in the mean time





echo "" 
echo "Re-compiling non-running local server code base as a sanity check"
echo ""

cd ~/checkout/minorGems
git pull --tags

cd ~/checkout/OneLife/server
git pull --tags

./configure 1
make


echo "About to post and tag server code."
echo ""
echo -n "Hit [ENTER] when ready: "
read



echo "" 
echo "Tagging live server code with OneLife_liveServer"
echo ""

cd ~/checkout/OneLife


git tag -fa OneLife_liveServer -m "Tag automatically generated by data-only diffBundle script."


echo "" 
echo "Pushing tag change to central git server"
echo ""

git push
git push origin -f --tags



echo "" 
echo "Tagging live minorGems code with OneLife_liveServer"
echo ""

cd ~/checkout/minorGems


git tag -fa OneLife_liveServer -m "Tag automatically generated by data-only diffBundle script."


echo "" 
echo "Pushing tag change to central git server"
echo ""

git push
git push origin -f --tags




~/checkout/OneLifeWorking/scripts/updateServerCodeStep1.sh

~/checkout/OneLifeWorking/scripts/updateServerCodeStep2.sh









echo "" 
echo "Done updating code on all servers."
echo ""
